build: false

  
environment:
  matrix:
    - CONDA: C:\Miniconda
    - CONDA: C:\Miniconda-x64
    - CONDA: C:\Miniconda36
    - CONDA: C:\Miniconda36-x64

init:
  - "ECHO %CONDA%"

install:
  - "set PATH=%CONDA%;%CONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - pip install numpy scipy h5py matplotlib fabio xfab pycifrw pillow --no-deps
  - pip install .

test_script:
  - cd test
  - python run_tests.py